### ISSUE TITLE
Generating a xs-security.json does not work

### ISSUE THREAD

**Issue by d066471** [SAP-samples/cloud-cap-risk-management#6]
Hi,

Generating a xs-security.json file via command **cds compile srv/risk-service.cds --to xsuaa > xs-security.json** fails with the following error:

`[INTERNAL ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined
    at Object.promisify (internal/util.js:290:11)
    at Object.<anonymous> (C:\Users\D066471\AppData\Roaming\npm\node_modules\@sap\cds-dk\lib\util\write.js:26:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.compile (C:\Users\D066471\AppData\Roaming\npm\node_modules\@sap\cds-dk\bin\compile\index.js:206:17)
    at Object.exec (C:\Users\D066471\AppData\Roaming\npm\node_modules\@sap\cds-dk\bin\cds.js:39:19)`

I have a dependency "@sap/cds": "^5" in my CAP project package.json.

Best regards,
Brijesh

**Comment by d066471** [comment]
Well with upgrading to @sap/cds-dk: 4.3.1, this issue does not happen.

**Comment by uwe-klinger** [comment]
Hi Brijesh,

I'm closing this issue, as it seems to be an already solved bug.

Best regards,
Uwe
